[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[rpc_endpoints]
c-chain = "http://localhost:9650/ext/bc/C/rpc"
# your-subnet = "http://localhost:9650/ext/bc/BASE58_BLOCKCHAIN_ID/rpc"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
